####################
# INTERFACE/SCREEN #
####################
# Window
WINDOW_LENGTH = 800
WINDOW_WIDTH = 600
SCALING = .5
########################
# INTERACTABLE ENTITY  #
########################
# Player
PLAYER_MOVEMENT_SPEED = 10
PLAYER_BULLET_SPEED = 10
PLAYER_PROP_DISTANCE = 15
PLAYER_SPRITE_OFFSET = 15
PLAYER_DEFAULT_HEALTH = 3
# Enemy
ENEMY_SPAWN_OFFSET = 25
ENEMY_MOVEMENT_SPEED = 3
ENEMY_SPAWN_TIMER = 1
# Boss
BOSS_MOVEMENT_SPEED = 1
BOSS_BULLET_SPEED = -3
# Background
BACKGROUND_HEIGHT = 2000
BACKGROUND_SCROLL_SPEED = 5
################
# TEXT STRINGS #
################
# Scoring
SCORE_POS_X = 10
SCORE_POS_Y = 10
SCORE_FONT_SIZE = 14
# Health
HEALTH_POS_X = 10
HEALTH_POS_Y = 30
HEALTH_FONT_SIZE = 14
