# Window
WINDOW_LENGTH = 800
WINDOW_WIDTH = 400
SCALING = .5
# Player
PLAYER_MOVEMENT_SPEED = 10
PLAYER_BULLET_SPEED = 10
PLAYER_PROP_DISTANCE = 15
# Enemy
ENEMY_SPAWN_OFFSET = 25
ENEMY_MOVEMENT_SPEED = 3
ENEMY_SPAWN_TIMER = 1
# Boss
BOSS_MOVEMENT_SPEED = 1
# Bullet
BULLET_SPEED = 10
# Scoring
SCORE_POS_X = 10
SCORE_POS_Y = 10
SCORE_FONT_SIZE = 14
# Background
BACKGROUND_HEIGHT = 1600
BACKGROUND_SCROLL_SPEED = 5
